# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir flask flask_cors requests

# Define environment variable
ENV FLASK_APP=subscriber.py
ENV FLASK_RUN_HOST=0.0.0.0

# The CMD command is removed to allow docker-compose to specify the command and arguments, including the port.
