# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install any needed packages specified in requirements.txt
RUN pip install Flask flask_cors requests

# Define environment variable
ENV FLASK_APP=subscriber.py
ENV FLASK_RUN_HOST=0.0.0.0

# Run subscriber.py when the container launches
CMD ["python3", "subscriber.py"]
