apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker1
  template:
    metadata:
      labels:
        app: broker1
    spec:
      containers:
        - name: broker1
          image: broker-image:latest
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: broker1-service
spec:
  selector:
    app: broker1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
