apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker1
  template:
    metadata:
      labels:
        app: broker1
    spec:
      containers:
        - name: broker1
          image: gurpreets1/unity-alert-kubernetes-deployment-broker1:1.0.0
          command: ["python3", "broker.py"]
          args: ["--port", "5000"]
          ports:
            - containerPort: 5000
          env:
            - name: BROKER_PORT
              value: "5000"

---
apiVersion: v1
kind: Service
metadata:
  name: broker1
spec:
  selector:
    app: broker1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
