# Broker3 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker3
  template:
    metadata:
      labels:
        app: broker3
    spec:
      containers:
        - name: broker3
          image: gurpreets1/unity-alert-kubernetes-deployment-broker1:1.0.0
          command: ["python3", "broker.py"]
          args: ["--port", "5002"]
          ports:
            - containerPort: 5002
          env:
            - name: BROKER_PORT
              value: "5002"
---
# Broker3 Service
apiVersion: v1
kind: Service
metadata:
  name: broker3
spec:
  selector:
    app: broker3
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
