# Broker2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker2
  template:
    metadata:
      labels:
        app: broker2
    spec:
      containers:
        - name: broker2
          image: your-docker-hub-username/unity-alert-broker2:latest
          ports:
            - containerPort: 5001
---
# Broker2 Service
apiVersion: v1
kind: Service
metadata:
  name: broker2
spec:
  selector:
    app: broker2
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
