apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
        - name: frontend2
          image: your-docker-hub-username/react-frontend:v1.0.0
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend2
spec:
  type: LoadBalancer
  selector:
    app: frontend2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
