apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-user1
  template:
    metadata:
      labels:
        app: frontend-user1
    spec:
      containers:
        - name: frontend
          image: gurpreets1/unity-alert-kubernetes-deployment-client:3.0.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: REACT_APP_SUBSCRIBER_IP
              value: "ab460142f76874e42b9d8ee0a46215c4-692867687.us-east-2.elb.amazonaws.com"
            - name: REACT_APP_SUBSCRIBER_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user1-service
spec:
  type: LoadBalancer
  ports:
    - port: 80 # External port
      targetPort: 3000 # Container port
  selector:
    app: frontend-user1
