apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-user2
  template:
    metadata:
      labels:
        app: frontend-user2
    spec:
      containers:
        - name: frontend
          image: gurpreets1/unity-alert-kubernetes-deployment-client:3.0.0
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: REACT_APP_SUBSCRIBER_IP
              value: "aadc4689cee4743478b5b15ba6db6fa5-120506552.us-east-2.elb.amazonaws.com"
            - name: REACT_APP_SUBSCRIBER_PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user2-service
spec:
  selector:
    app: frontend-user2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: LoadBalancer
