apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-user2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-user2
  template:
    metadata:
      labels:
        app: frontend-user2
    spec:
      containers:
        - name: frontend
          image: your-frontend-image:latest
          ports:
            - containerPort: 81
          env:
            - name: SUBSCRIBER_IP
              value: "subscriber2" # Adjust if necessary
            - name: SUBSCRIBER_PORT
              value: "8001"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-user2-service
spec:
  selector:
    app: frontend-user2
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  type: LoadBalancer
