apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
spec:
  replicas: 3 # Start with 3 instances
  selector:
    matchLabels:
      app: broker
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
        - name: broker
          image: myflaskapp
          args: ["python3", "subscriber.py", "--port", "5000"]
          ports:
            - containerPort: 5000
