# Use an official Python runtime as a parent image
FROM python:3.9

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install Flask flask_cors requests

# Make port available to the world outside this container
EXPOSE 5000


# Run broker.py when the container launches
CMD ["python3", "broker.py"]
