# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the dependencies
# If you have a requirements.txt file, uncomment the next line and add your dependencies there
# RUN pip install --no-cache-dir -r requirements.txt
# Otherwise, install directly
RUN pip install Flask flask_cors requests

# Expose the port the app runs on. Adjust this if you use a different port.
EXPOSE 5000

# Define environment variables for configuration (optional)
# ENV VARIABLE_NAME=value

# Command to run the Flask application
# Using the `flask run` command and specifying the host to listen on all network interfaces
CMD ["flask", "run", "--host=0.0.0.0"]
