# Use an official Python runtime as a base image
FROM python:3.9

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN pip install Flask flask_cors requests

# Expose the port the app runs on. Adjust this if you use a different port.
EXPOSE 5000
