# Subscriber1 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber1
  template:
    metadata:
      labels:
        app: subscriber1
    spec:
      containers:
        - name: subscriber1
          image: gurpreets1/unity-alert-kubernetes-deployment-subscriber1:6.0.0
          command: ["python3", "subscriber.py"]
          args: ["--port", "8000", "--sub_name", "subscriber1"]
          ports:
            - containerPort: 8000
          env:
            - name: SUBSCRIBER_PORT
              value: "8000"

---
# Subscriber1 Internal Service
apiVersion: v1
kind: Service
metadata:
  name: subscriber1
spec:
  selector:
    app: subscriber1
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

---
# Subscriber1 External Service
apiVersion: v1
kind: Service
metadata:
  name: subscriber1-external # A more descriptive name for external access
spec:
  type: LoadBalancer
  selector:
    app: subscriber1
  ports:
    - protocol: TCP
      port: 80 # Standard HTTP port for easier access
      targetPort: 8000
