apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber2
  template:
    metadata:
      labels:
        app: subscriber2
    spec:
      containers:
        - name: subscriber2
          image: gurpreets1/unity-alert-kubernetes-deployment-subscriber1:5.0.0
          command: ["python3", "subscriber.py"]
          args: ["--port", "8001"]
          ports:
            - containerPort: 8001
          env:
            - name: SUBSCRIBER_PORT
              value: "8001"

---
apiVersion: v1
kind: Service
metadata:
  name: subscriber2
spec:
  selector:
    app: subscriber2
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
